services:
  api:
    build: ./api
    restart: on-failure:10
    environment:
      - ENV=prod
    ports:
      - 8080:8080
    networks:
      - mks
      
  database:
    image: postgres
    restart: always
    env_file: ./api/.env
    ports:
      - 5432:5432
    networks:
      - mks
    
networks:
  mks:
    driver: bridge